### ISSUE TITLE
Can't import from @haensl/google-analytics/measurement-protocol

### ISSUE THREAD

**Issue by stoefln** [haensl/google-analytics#10]
<img width="969" alt="image" src="https://github.com/user-attachments/assets/3c7e3fb3-8d40-415d-929a-5a5c2b1a754f">

What am I doing wrong?
I am on @haensl/google-analytics@1.2.0

**Comment by haensl** [comment]
Hi Stephan,

unfortunately that's hard to say from this screenshot alone. What's your project and bundler setup? What's the error thrown? I'm not writing TypeScript, so missing type declarations won't go away....

**Comment by stoefln** [comment]
I don't think it's the bundler to be honest, because the error is shown in Visual Studio Code.
I also don't see a subdirectory in your package:
<img width="913" alt="image" src="https://github.com/user-attachments/assets/dc62c62d-c48b-434b-9d7d-66a2ee6ff0a7">

**Comment by haensl** [comment]
Hi Stephan,

this should be fixed via 1.2.2.

**Comment by stoefln** [comment]
Thanks a lot for the quick fix!!
